config/routes.rb
GitTest::Application.routes.draw do
  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:email]
    @user.password = params[:password]
    
    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.email = params[:email]
    @user.password = params[:password]
    
    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to users_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= text_field_tag :password, @user.password %>
  </div>

  
  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= text_field_tag :password %>
  </div>


  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>